version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    command: >
      bash -c "rm -rf tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/share_videos/
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres@db
    tty: true
    stdin_open: true
    depends_on:
      - db
      - redis
  db:
    image: postgres:10.3-alpine
  redis:
    image: redis:4.0-alpine
    command: redis-server
    ports:
      - "6379:6379"
  cable:
    depends_on:
      - redis
    build: .
    command: bundle exec puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    volumes:
      - .:/usr/src/share_videos/
volumes:
  redis:
  postgres: